# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2022 Oplus. All rights reserved.

# Qcom platform feature

#ifdef OPLUS_FEATURE_PMIC_MONITOR
obj-$(CONFIG_OPLUS_FEATURE_PMIC_MONITOR) += qcom/qcom_pmic_monitor/
#endif /* OPLUS_FEATURE_PMIC_MONITOR */

# common feature

#ifdef OPLUS_FEATURE_KEYEVENT_HANDLER
obj-$(CONFIG_OPLUS_FEATURE_KEYEVENT_HANDLER) += common/keyevent_handler/
#endif /* OPLUS_FEATURE_KEYEVENT_HANDLER */
